#
# EXECUTION (from placement-operator repo root):
#
#  kubectl-kuttl test --config ${PLACEMENT_KUTTL_CONF} ${PLACEMENT_KUTTL_DIR} 
#
#  PLACEMENT_KUTTL_CONF: path to placement-operator repo
#  PLACEMENT_KUTTL_DIR: path to current file 'kuttl-test.yaml' (top directory of placement-operator repo)
#
# ASSUMPTIONS:
#
# 1. Latest version of kuttl is installed at /usr/local/bin/kubectl-kuttl
#    - wget https://github.com/kudobuilder/kuttl/releases/download/v0.11.1/kubectl-kuttl_0.11.1_linux_x86_64
#    - mv kubectl-kuttl_0.11.1_linux_x86_64 /usr/local/bin/kubectl-kuttl
#    - chmod 755 /usr/local/bin/kubectl-kuttl
# 2. An OCP 4.10+ CRC cluster with Podified Operators has been deployed
# 3. CLI user has access to $KUBECONFIG
# 4. The environment variable INSTALL_YAMLS is set to the the path of the
#    install_yamls repo

apiVersion: kuttl.dev/v1beta1
kind: TestSuite
reportFormat: JSON
reportName: kuttl-test-placement
namespace: openstack
timeout: 180
parallel: 1
suppress:
  - events
