apiVersion: placement.openstack.org/v1beta1
kind: PlacementAPI
metadata:
  name: placement
spec:
  serviceUser: placement
  containerImage: quay.io/podified-antelope-centos9/openstack-placement-api:current-podified
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: placement
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  replicas: 1
  secret: placement-secret
  #resources:
  #  requests:
  #    memory: "500Mi"
  #    cpu: "1.0"
